### ISSUE TITLE
Use '.' to split

### ISSUE THREAD

**Issue by sen1** [cwsvensson/pwp-capstones#2]
You have:
```
word_counts =    [len(one_sentence.replace(".", " ").split()) for one_sentence in sentences_breakdown 
                   if len(one_sentence.replace(".", " ").split()) > 0]
```
By default `split()` splits on blank space but you can define a separation if you want.
```
a = 'One entence. Two sentence'
a.split('.')
['One entence', ' Two sentence']
```

So you won't need to first replace '.' with a blank then split. Also, we generally assume that a sentence cannot be a length 0, so second if statement is redundant.
```
sentences = no_exclaim.split('.')
```

**Comment by cwsvensson** [comment]
Thank you for the prompt feedback.  Most of it was spot on, but one item did jump out at me.  Please, let me walk you through it, and by doing so, I hope that this doesn’t jeopardize my score…

   First, it turns out that the line:

word_counts = [len(one_sentence.replace(".", " ").split()) for one_sentence in sentences_breakdown if len(one_sentence.replace(".", " ").split()) > 0]

does have one redundancy that you pointed out.  Since I had already broken down the sentences into a list, the “.” (periods) were all gone.  So the line:

word_counts = [len(one_sentence.split()) for one_sentence in entences_breakdown if len(one_sentence.split()) > 0]

works just as well (= gives the same result). Hence – redundancy.  I already broke the sentences down, and I am now doing a word count.  However, your complaint about the redundant “if” clause is, incorrect.  We must not assume that sentences can’t be zero length.  Zero length sentences are generated from two anomalies.  The first comes from the murder note having a poorly constructed sentence:

“AND FOR WHAT?!”

Note the use of the question mark next to the exclamation mark.  This becomes two periods, and the second period, if not cleaned, generates an empty sentence.  The other problem is that the use of “split(“.”) also generates an empty sentence at the end of the new list, if the note ends in a period.  All of the notes do (after cleaning). (Of course, while some murderers have been busted for tax evasion, to my knowledge no one ever got busted for bad grammar.)  So, the bottom line is that removing the “if” clause does change the calculations, and therefore isn’t redundant.  It’s simple, the word count stays the same, but empty sentences artificially lower the calculation of the average sentence length.  Test it with my code.  Remove the clause and see what happens!

   You pointed out the I did (in your earlier comment) use “.replace(‘..’, ‘.’)” and it is true that this is unnecessary, but that too is only because of the “if” clause that removes empty sentences.  At first, it was necessary because of the “?!”, but inclusion of the “if” clause (above) rendered this replace statement useless after-the-fact.
