### ISSUE TITLE
Rubric Score

### ISSUE THREAD

**Issue by sen1** [cwsvensson/pwp-capstones#3]
### Criteria 1: Valid Python Code
* 4 (Exceeds Expectations)
* Very nice coding. Remember to remove test print out statements once you are done with them. Make it clean.
 
### Criteria 2: Implementation of Project Requirements
* 4 (Exceeds Expectations) 
* All worked as expected.
 
### Criteria 3: Software Architecture
* 4 (Exceeds Expectations) 
* Nice use of dictionaries, and logical functions.
 
### Criteria 4: Uses Python Language Features
* 4 (Exceeds Expectations) 
* Nicely done.

### Criteria 5: Produces Accurate Output
* 4 (Exceeds Expectations) 

 
### Overall Score: 20/20
Excellent work. 👏

**Comment by cwsvensson** [comment]
Thank you, but if I am to be critical of my own code, I would draw attention to the routine:

frequency_comparison(table1, table2)

Note that inside that function, table1 is not modified and table2 is.  The “.pop()” used on table2 changes the dictionary and this is bad coding form.  Of course, both arguments come in passed by reference, and therefore modifications to the dictionaries will persist.  I had to be careful to always call the murder note first, so as not to modify it.  The purpose of the function was to come up with a count based calculation, not to modify the data of the class variables.

   However, this wasn’t covered in this course and neither was cloning, so I let it go at this level.

   As for the course itself, I got the impression that it wasn’t completed and tested when we started it.  This came from two observations:
1)	Not all weeks were available from the start, and
2)	Course material mistakes were more numerous towards the latter weeks.

So, I felt like we were Lab Rats as well as students.  My strategy was to let the leaders run first and catch the major mistakes, and then stay close behind them.  I also plan on completing, but not submitting, the second project – for my own benefit.  I also took note of the many links offered during the course, by the Moderators on Slack.  Some of those web sites, however, try to sign us up onto spam lists.  Since we are paying for the course, this seems to me to be bad form.  The sites should be vetted, and in some cases the information stripped and offered without a link.

In general though, it was a lot for the money.

Thanks,
Chris
